# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudantias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayudantias',
            name='hora',
        ),
        migrations.AddField(
            model_name='ayudantias',
            name='horaFin',
            field=models.TimeField(default='00:00', verbose_name='Finaliza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ayudantias',
            name='horaInicio',
            field=models.TimeField(default='00:00', verbose_name='Empieza'),
            preserve_default=False,
        ),
    ]
