# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudantias', '0002_auto_20170222_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIembed',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('embed', models.CharField(max_length=500)),
            ],
        ),
    ]
