# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayudantias', '0003_apiembed'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='embed',
            field=models.ForeignKey(default='fiec', on_delete=django.db.models.deletion.CASCADE, to='ayudantias.APIembed'),
        ),
    ]
