# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from django.core.management import call_command

def loadfixture(apps, schema_editor):
    call_command('loaddata', 'initial_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('ayudantias', '0003_apiembed'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
        migrations.AddField(
            model_name='aulas',
            name='embed',
            field=models.ForeignKey(default='fiec', on_delete=django.db.models.deletion.CASCADE, to='ayudantias.APIembed'),

        ),
    ]
