# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto_archivo', models.FileField(blank=True, upload_to='', verbose_name='Foto (Archivo)')),
                ('foto_url', models.URLField(blank=True, verbose_name='Foto (URL)')),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto_archivo', models.FileField(blank=True, upload_to='', verbose_name='Foto (Archivo)')),
                ('foto_url', models.URLField(blank=True, verbose_name='Foto (URL)')),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
