# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', tinymce.models.HTMLField()),
            ],
        ),
    ]
