# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0002_tiporecurso_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiporecurso',
            old_name='img',
            new_name='icono',
        ),
    ]
