# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models

from django.core.management import call_command

def loadfixture(apps, schema_editor):
    call_command('loaddata', 'initial_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0003_auto_20170222_0506'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
        migrations.RemoveField(
            model_name='recurso',
            name='file',
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
