# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:03
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
    ]
