# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 03:52
from __future__ import unicode_literals

from django.db import migrations, models

from django.core.management import call_command

def loadfixture(apps, schema_editor):
    call_command('loaddata', 'initial_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20170301_2245'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
        migrations.AlterField(
            model_name='seccion',
            name='estado',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], max_length=8),
        ),
    ]
