# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20170301_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='estado',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], max_length=8),
        ),
    ]
